# Generated by Django 5.1.2 on 2024-10-13 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_team_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
